FROM golang:latest

RUN mkdir -p /go/src/github.com/gilangr301102/Tubes2_Gass/src/backend
ADD . /go/src/github.com/gilangr301102/Tubes2_Gass/src/backend
WORKDIR /go/src/github.com/gilangr301102/Tubes2_Gass/src/backend